# frozen_string_literal: true

require "minitest/test_task"

Minitest::TestTask.create

require "standard/rake"

require "plushie"
require_relative "lib/crash_extension"

Plushie.configure do |config|
  config.widgets = [CrashExtension]
end

require "plushie/rake"

task default: %i[test standard]
