#!/usr/bin/env bash
set -euo pipefail

if [ "$#" -ne 1 ]; then
  echo "usage: $0 DEMO_DIR" >&2
  exit 2
fi

DEMO_DIR="$(cd "$1" && pwd)"
DEFAULT_PLUSHIE_RUST_DIR="$(cd "$DEMO_DIR/../../../plushie-rust" 2>/dev/null && pwd || true)"
PLUSHIE_RUST_SOURCE_PATH="${PLUSHIE_RUST_SOURCE_PATH:-$DEFAULT_PLUSHIE_RUST_DIR}"

if [ -z "$PLUSHIE_RUST_SOURCE_PATH" ] || [ ! -f "$PLUSHIE_RUST_SOURCE_PATH/Cargo.toml" ]; then
  exit 0
fi

mkdir -p "$DEMO_DIR/.cargo"
CONFIG="$DEMO_DIR/.cargo/config.toml"

{
  printf '# Auto-generated by rust/scripts/prepare_local_source.sh. Do not edit.\n'
  printf '# Redirects Rust demo Plushie deps to a local checkout.\n\n'
  printf '[patch.crates-io]\n'
  for crate in \
    plushie \
    plushie-core \
    plushie-core-macros \
    plushie-renderer-lib \
    plushie-renderer-engine \
    plushie-widget-sdk; do
    printf '%s = { path = "%s/crates/%s" }\n' "$crate" "$PLUSHIE_RUST_SOURCE_PATH" "$crate"
  done
} > "$CONFIG"
