name = "notes"
version = "0.1.0"
target = "erlang"
plushie_rust_version = "0.6.1"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_erlang = ">= 0.29.0 and < 2.0.0"
plushie_gleam = ">= 0.6.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
