#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEMO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
DEFAULT_PLUSHIE_RUST_DIR="$(cd "$DEMO_DIR/../../../plushie-rust" 2>/dev/null && pwd || true)"
PLUSHIE_RUST_SOURCE_PATH="${PLUSHIE_RUST_SOURCE_PATH:-$DEFAULT_PLUSHIE_RUST_DIR}"

cleanup_generated_cargo_config() {
  local config="$DEMO_DIR/.cargo/config.toml"

  if [ -f "$config" ] &&
    grep -Eq 'Auto-generated by `cargo plushie (build|package assemble)`' "$config"; then
    rm -f "$config"
    rmdir "$DEMO_DIR/.cargo" 2>/dev/null || true
  fi
}

trap cleanup_generated_cargo_config EXIT

echo "==> Building Rust shared launcher payload..."
if [ -n "$PLUSHIE_RUST_SOURCE_PATH" ] && [ -f "$PLUSHIE_RUST_SOURCE_PATH/Cargo.toml" ]; then
  cargo run -q -p cargo-plushie \
    --manifest-path "$PLUSHIE_RUST_SOURCE_PATH/Cargo.toml" \
    -- package assemble \
    --manifest-path "$DEMO_DIR/Cargo.toml" \
    --bin plushie_pad \
    --out-dir "$DEMO_DIR/dist" \
    --release \
    --no-default-features \
    --features wire \
else
  cargo plushie package assemble \
    --manifest-path "$DEMO_DIR/Cargo.toml" \
    --bin plushie_pad \
    --out-dir "$DEMO_DIR/dist" \
    --release \
    --no-default-features \
    --features wire
fi

echo ""
echo "Payload manifest: $DEMO_DIR/dist/plushie-package.toml"
echo "Payload archive:  $DEMO_DIR/dist/payload.tar.zst"
echo "Package handoff:  cargo plushie package portable --manifest $DEMO_DIR/dist/plushie-package.toml --release"
