//! Plushie Pad Elm loop.
//!
//! The pad is a single-window Plushie app. The model carries the
//! experiment gallery, the selected index, and a bounded event
//! log. `view` renders a four-pane layout: sidebar, source,
//! preview, and event log underneath. `update` handles two kinds
//! of events: sidebar clicks (switch experiment) and events that
//! originate inside the preview pane (forward to the current
//! experiment, then log).

use plushie::prelude::*;
use plushie::settings::Settings;

use crate::experiments::{Experiment, build_gallery};
use crate::ui;

/// Maximum number of lines kept in the event log pane.
const EVENT_LOG_CAPACITY: usize = 20;

/// Maximum length of an individual log line before it's truncated.
/// Plushie's event enum is wordy when debug-printed, and the log
/// column is narrow; trimming keeps things readable.
const EVENT_LOG_MAX_LEN: usize = 140;

#[derive(Clone)]
pub struct Model {
    pub selected: usize,
    pub experiments: Vec<Box<dyn Experiment>>,
    pub event_log: Vec<String>,
}

impl Model {
    fn current(&self) -> &dyn Experiment {
        self.experiments[self.selected].as_ref()
    }

    fn current_mut(&mut self) -> &mut dyn Experiment {
        self.experiments[self.selected].as_mut()
    }

    fn push_log(&mut self, entry: String) {
        let trimmed = if entry.len() > EVENT_LOG_MAX_LEN {
            let mut s = entry;
            s.truncate(EVENT_LOG_MAX_LEN);
            s.push_str("...");
            s
        } else {
            entry
        };
        self.event_log.insert(0, trimmed);
        if self.event_log.len() > EVENT_LOG_CAPACITY {
            self.event_log.truncate(EVENT_LOG_CAPACITY);
        }
    }
}

pub struct PadApp;

impl App for PadApp {
    type Model = Model;

    fn init() -> (Self::Model, Command) {
        let model = Model {
            selected: 0,
            experiments: build_gallery(),
            event_log: Vec::new(),
        };
        (model, Command::none())
    }

    fn settings() -> Settings {
        Settings {
            theme: Some(Theme::from("dark")),
            ..Settings::default()
        }
    }

    fn update(model: &Self::Model, event: Event) -> (Self::Model, Command) {
        let mut model = model.clone();

        // Sidebar click: switch experiments. `pick_<N>` IDs are
        // generated by `ui::sidebar::view`; we parse the trailing
        // number back out here. We also log the sidebar events
        // so the flow is visible in the event pane.
        if let Some(Click(id)) = event.widget_match()
            && let Some(rest) = id.strip_prefix("pick_")
            && let Ok(index) = rest.parse::<usize>()
            && index < model.experiments.len()
        {
            model.selected = index;
            model.push_log(format!("pad: selected {}", model.experiments[index].name()));
            return (model, Command::none());
        }

        // Events from inside the preview pane go to the current
        // experiment. The scope chain for a preview-originated
        // event always contains the literal string `preview` (the
        // ID of the wrapper container), so we use that as the
        // forwarding signal.
        let from_preview = event
            .scope()
            .map(|s| s.iter().any(|hop| hop == "preview"))
            .unwrap_or(false);
        if from_preview {
            let _ = model.current_mut().update(&event);
        }

        model.push_log(format!("{event:?}"));
        (model, Command::none())
    }

    fn view(model: &Self::Model, _widgets: &mut WidgetRegistrar) -> ViewList {
        window("main")
            .title("Plushie Pad")
            .size(1200.0, 800.0)
            .theme(Theme::from("dark"))
            .child(
                column()
                    .id("root")
                    .width(Fill)
                    .height(Fill)
                    .child(
                        row()
                            .id("panes")
                            .width(Fill)
                            .height(Fill)
                            .child(ui::sidebar::view(&model.experiments, model.selected))
                            .child(ui::source_view::view(model.current().source()))
                            .child(ui::preview::view(model.current())),
                    )
                    .child(ui::event_log::view(&model.event_log)),
            )
            .into()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use plushie::test::TestSession;

    // ---------------------------------------------------------------------------
    // init
    // ---------------------------------------------------------------------------

    #[test]
    fn init_selects_first_experiment() {
        let session = TestSession::<PadApp>::start();
        assert_eq!(session.model().selected, 0);
    }

    #[test]
    fn init_event_log_is_empty() {
        let session = TestSession::<PadApp>::start();
        assert!(session.model().event_log.is_empty());
    }

    #[test]
    fn init_loads_all_experiments() {
        let session = TestSession::<PadApp>::start();
        assert_eq!(session.model().experiments.len(), 5);
    }

    // ---------------------------------------------------------------------------
    // view structure
    // ---------------------------------------------------------------------------

    #[test]
    fn view_has_sidebar() {
        let session = TestSession::<PadApp>::start();
        session.assert_exists("sidebar");
    }

    #[test]
    fn view_has_source_pane() {
        let session = TestSession::<PadApp>::start();
        session.assert_exists("source");
    }

    #[test]
    fn view_has_preview_pane() {
        let session = TestSession::<PadApp>::start();
        session.assert_exists("preview");
    }

    #[test]
    fn view_has_event_log() {
        let session = TestSession::<PadApp>::start();
        session.assert_exists("event_log");
    }

    #[test]
    fn sidebar_has_pick_button_for_each_experiment() {
        let session = TestSession::<PadApp>::start();
        for i in 0..5 {
            session.assert_exists(format!("pick_{i}").as_str());
        }
    }

    // ---------------------------------------------------------------------------
    // sidebar selection
    // ---------------------------------------------------------------------------

    #[test]
    fn clicking_pick_changes_selected() {
        let mut session = TestSession::<PadApp>::start();
        session.click("pick_2");
        assert_eq!(session.model().selected, 2);
    }

    #[test]
    fn clicking_pick_logs_selection() {
        let mut session = TestSession::<PadApp>::start();
        session.click("pick_1");
        let log = &session.model().event_log;
        assert!(!log.is_empty());
        assert!(
            log[0].contains("selected counter"),
            "expected 'selected counter' in log, got: {:?}",
            log[0]
        );
    }

    #[test]
    fn clicking_last_experiment() {
        let mut session = TestSession::<PadApp>::start();
        session.click("pick_4");
        assert_eq!(session.model().selected, 4);
        assert_eq!(session.model().experiments[4].name(), "form");
    }

    // ---------------------------------------------------------------------------
    // event log: push_log logic tested directly
    // ---------------------------------------------------------------------------

    #[test]
    fn push_log_adds_entry_at_front() {
        let mut model = Model {
            selected: 0,
            experiments: crate::experiments::build_gallery(),
            event_log: Vec::new(),
        };
        model.push_log("first".into());
        model.push_log("second".into());
        assert_eq!(model.event_log[0], "second");
        assert_eq!(model.event_log[1], "first");
    }

    #[test]
    fn push_log_caps_at_capacity() {
        let mut model = Model {
            selected: 0,
            experiments: crate::experiments::build_gallery(),
            event_log: Vec::new(),
        };
        for i in 0..=EVENT_LOG_CAPACITY + 5 {
            model.push_log(format!("entry {i}"));
        }
        assert_eq!(model.event_log.len(), EVENT_LOG_CAPACITY);
    }

    #[test]
    fn push_log_truncates_long_entries() {
        let long = "x".repeat(EVENT_LOG_MAX_LEN + 50);
        let mut model = Model {
            selected: 0,
            experiments: crate::experiments::build_gallery(),
            event_log: Vec::new(),
        };
        model.push_log(long);
        let entry = &model.event_log[0];
        assert!(entry.ends_with("..."));
        assert!(entry.len() <= EVENT_LOG_MAX_LEN + 3);
    }

    #[test]
    fn push_log_preserves_short_entries() {
        let short = "hello";
        let mut model = Model {
            selected: 0,
            experiments: crate::experiments::build_gallery(),
            event_log: Vec::new(),
        };
        model.push_log(short.into());
        assert_eq!(model.event_log[0], short);
    }

    // ---------------------------------------------------------------------------
    // preview routing
    // ---------------------------------------------------------------------------

    #[test]
    fn preview_click_routes_to_hello_experiment() {
        let mut session = TestSession::<PadApp>::start();
        // "wave" is inside the preview container, so it gets routed to
        // the current experiment (hello). Check the event log for routing
        // rather than inspecting experiment state (experiments are opaque
        // dyn trait objects from this scope).
        let log_before = session.model().event_log.len();
        session.click("wave");
        assert!(session.model().event_log.len() > log_before);
    }
}
