//! Plushie Pad Elm loop.
//!
//! The pad is a single-window Plushie app. The model carries the
//! experiment gallery, the selected index, and a bounded event
//! log. `view` renders a four-pane layout: sidebar, source,
//! preview, and event log underneath. `update` handles two kinds
//! of events: sidebar clicks (switch experiment) and events that
//! originate inside the preview pane (forward to the current
//! experiment, then log).

use plushie::prelude::*;
use plushie::settings::Settings;

use crate::experiments::{build_gallery, Experiment};
use crate::ui;

/// Maximum number of lines kept in the event log pane.
const EVENT_LOG_CAPACITY: usize = 20;

/// Maximum length of an individual log line before it's truncated.
/// Plushie's event enum is wordy when debug-printed, and the log
/// column is narrow; trimming keeps things readable.
const EVENT_LOG_MAX_LEN: usize = 140;

pub struct Model {
    pub selected: usize,
    pub experiments: Vec<Box<dyn Experiment>>,
    pub event_log: Vec<String>,
}

impl Model {
    fn current(&self) -> &dyn Experiment {
        self.experiments[self.selected].as_ref()
    }

    fn current_mut(&mut self) -> &mut dyn Experiment {
        self.experiments[self.selected].as_mut()
    }

    fn push_log(&mut self, entry: String) {
        let trimmed = if entry.len() > EVENT_LOG_MAX_LEN {
            let mut s = entry;
            s.truncate(EVENT_LOG_MAX_LEN);
            s.push_str("...");
            s
        } else {
            entry
        };
        self.event_log.insert(0, trimmed);
        if self.event_log.len() > EVENT_LOG_CAPACITY {
            self.event_log.truncate(EVENT_LOG_CAPACITY);
        }
    }
}

pub struct PadApp;

impl App for PadApp {
    type Model = Model;

    fn init() -> (Self::Model, Command) {
        let model = Model {
            selected: 0,
            experiments: build_gallery(),
            event_log: Vec::new(),
        };
        (model, Command::none())
    }

    fn settings() -> Settings {
        Settings {
            theme: Some(Theme::from("dark")),
            ..Settings::default()
        }
    }

    fn update(model: &mut Self::Model, event: Event) -> Command {
        // Sidebar click: switch experiments. `pick_<N>` IDs are
        // generated by `ui::sidebar::view`; we parse the trailing
        // number back out here. We also log the sidebar events
        // so the flow is visible in the event pane.
        if let Some(Click(id)) = event.widget_match()
            && let Some(rest) = id.strip_prefix("pick_")
            && let Ok(index) = rest.parse::<usize>()
            && index < model.experiments.len()
        {
            model.selected = index;
            model.push_log(format!("pad: selected {}", model.experiments[index].name()));
            return Command::none();
        }

        // Events from inside the preview pane go to the current
        // experiment. The scope chain for a preview-originated
        // event always contains the literal string `preview` (the
        // ID of the wrapper container), so we use that as the
        // forwarding signal.
        let from_preview = event
            .scope()
            .map(|s| s.iter().any(|hop| hop == "preview"))
            .unwrap_or(false);
        if from_preview {
            let _ = model.current_mut().update(&event);
        }

        model.push_log(format!("{event:?}"));
        Command::none()
    }

    fn view(model: &Self::Model, _widgets: &mut WidgetRegistrar) -> ViewList {
        window("main")
            .title("Plushie Pad")
            .size(1200.0, 800.0)
            .theme(Theme::from("dark"))
            .child(
                column()
                    .id("root")
                    .width(Fill)
                    .height(Fill)
                    .child(
                        row()
                            .id("panes")
                            .width(Fill)
                            .height(Fill)
                            .child(ui::sidebar::view(&model.experiments, model.selected))
                            .child(ui::source_view::view(model.current().source()))
                            .child(ui::preview::view(model.current())),
                    )
                    .child(ui::event_log::view(&model.event_log)),
            )
            .into()
    }
}
