# frozen_string_literal: true

source "https://rubygems.org"

gem "plushie", path: "../../../plushie-ruby"

group :development, :test do
  gem "minitest", "~> 5.16"
  gem "standard", "~> 1.3"
  gem "rake", "~> 13.0"
end
